### ISSUE TITLE
removing hard-coding of 'auth0' as provider

### ISSUE THREAD

**Issue by tacomanator** [LordZardeck/PAW-Auth0TokenDynamicValue#6]
Was thinking to remove hard-coded `auth0|` prepended to `sub` and replace it with a provider dropdown, but there are too many providers for a dropdown.

Instead, what do you think about removing `auth0|` so that people can specify the full `userId` in the field (e.g. `auth0|123456` or `google-oauth2|123456`)?

**Comment by LordZardeck** [comment]
I actually like the idea of a drop down, providing a few options, probably the most common, then a final option of "custom" which just takes an input string to be the exact sub. This way we can extend with more providers as they are popular enough to make sense (or just bored enough to add to them), but still have it open enough for any provider down the road

When I originally built this for myself, I wasn't using the other providers, and forgot to take in account the other providers.

**Comment by tacomanator** [comment]
That's a good idea, since it would account for any providers. However, most of the time people are going to be copying and pasting the `user_id`, which includes the provider, from the dashboard or their database. A dropdown actually adds work rather than takes it away, and without tangible benefit. It could also make dynamic value integrations harder in that the provider must be stripped from a `user_id` before sending it to this extension.

**Comment by LordZardeck** [comment]
Hmm, I remember having to copy just the user_id without the provider, which is why I originally prepended it. I need to do some testing with Auth0 again and investigate. I see 2 things here:

1. The hard-coded `auth0|` needs to be removed, no matter what
2. Depending on the common use case, we either need to just have a simple input box, or provide a drop down with sample providers that has an option to just enter in a simple input box

With those 2 criteria, it makes sense to me to that we remove the hard-coding now, and add the extra feature in IF it makes sense. However, due to the previous code expecting the provider to be absent, I'd say for backwards compatibility that we search the input, and if no provider is found, then we still pre-pend it. This will ensure it works going forward for those still using the old `sub` style.
